site_name: Mégra Documentation
site_url: https://megra-doc.readthedocs.io/
nav:
    - 'Home' : 'index.md'
    - 'User Guide' :
        - 'Installation' : 'installation.md'
        - 'Audio Configuration' : 'audio-configuration.md'
        - 'Important Folders' : 'folders.md'
        - 'Using Samples' : 'using-samples.md'
    - 'Tutorial':
        - '1. Soundcheck' : 'tutorial/soundcheck.md'
        - '2. Sequence Generators & Contexts' : 'tutorial/sequence-generators-and-contexts.md'
        - '3. Sequence Generator Types' : 'tutorial/sequence-generator-types.md'
        - '4. Modifying the Event Stream' : 'tutorial/modifying-the-event-stream.md'
        - '5. Modifying Generators' : 'tutorial/modifying-sequence-generators.md'
        - '6. Layering Generators' : 'tutorial/multiplying-generators.md'
        - '7. LFOs and Continuous Modulators' : 'tutorial/lfos-and-continuous-time-modulators.md'
        - '8. Parts and Control Events' : 'tutorial/parts-and-control-events.md'
        - '9. Recording Your Sessions' : 'tutorial/recording.md'
        - '10. Final Remarks' : 'tutorial/final-remarks.md'
    - 'Function Reference' :
        - 'Sound Events' : 'function-reference/sound-events.md'
        - 'Control Events' : 'function-reference/control-events.md'
        - 'Sequence Generators' : 'function-reference/sequence-generators.md'
        - 'Generator Modifiers' : 'function-reference/generator-modifiers.md'
        - 'Generator Multiplyers' : 'function-reference/generator-multiplyers.md'
        - 'Discrete Parameter Modifiers' : 'function-reference/discrete-parameter-modifiers.md'
        - 'Continuous Modulators' : 'function-reference/continous-modulators.md'
        - 'Applicators' : 'function-reference/applicators.md'
        - 'Global Commands' : 'function-reference/global-commands.md'
theme:
    name: readthedocs    
