site_name: Mégra Documentation
site_url: https://megra-doc.readthedocs.io/
nav:
    - 'Home' : 'index.md'
    - 'User Guide' :
        - 'Installation' : 'installation.md'
        - 'Audio Configuration' : 'audio-configuration.md'
        - 'Important Folders' : 'folders.md'
        - 'The Startup File' : 'startup-file.md'
        - 'Using Samples' : 'using-samples.md'
        - 'The Editor' : 'editor.md'
    - 'Tutorial':
        - '1. Soundcheck' : 'tutorial/soundcheck.md'
        - '2. Making Sound' : 'tutorial/making-sound.md'
        - '3. Organizing Sound' : 'tutorial/organizing-sound.md'
        - '4. Modifying Sound' : 'tutorial/modifying-sound.md'
        - '5. Modifying Structure' : 'tutorial/modifying-structure.md'
        - '6. Layering Sound' : 'tutorial/layering-sound.md'
        - '7. LFOs and Continuous Modulators' : 'tutorial/lfos-and-continuous-time-modulators.md'
        - '8. Event Arithmetic' : 'tutorial/event-arithmetic.md'
        - '9. Parts and Control Events' : 'tutorial/parts-and-control-events.md'
        - '10. Using Live Sound Input' : 'tutorial/using-live-input.md'
        - '11. Using MIDI Input' : 'tutorial/using-midi-input.md'
        - '12. Using OSC' : 'tutorial/using-osc.md'
        - '13. Using Wavetables' : 'tutorial/using-wavetables.md'
        - '14. Multichannel Sound' : 'tutorial/multichannel-sound.md'
        - '15. Recording Your Sessions' : 'tutorial/recording.md'
        - '16. Final Remarks' : 'tutorial/final-remarks.md'
    - 'Function Reference' :
        - 'Arithmetic Events' : 'function-reference/arithmetic-events.md'
        - 'Applicators' : 'function-reference/applicators.md'
        - 'Continuous Modulators' : 'function-reference/continuous-modulators.md'
        - 'Control Events' : 'function-reference/control-events.md'
        - 'Discrete Parameter Modifiers' : 'function-reference/discrete-parameter-modifiers.md'
        - 'Generator Modifiers' : 'function-reference/generator-modifiers.md'
        - 'Generator Multiplyers' : 'function-reference/generator-multiplyers.md'
        - 'Global Commands' : 'function-reference/global-commands.md'
        - 'Language Constructs' : 'function-reference/language-constructs.md'
        - 'Note Event' : 'function-reference/note-event.md'
        - 'Sequence Generators' : 'function-reference/sequence-generators.md'
        - 'Shorthand Syntax' : 'function-reference/shorthand-syntax.md'
        - 'Sound Events' : 'function-reference/sound-events.md'
theme:
    name: readthedocs    
